# Generated by Django 3.2.3 on 2021-05-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Djangoforum', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
